<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete course');

if(isset($_GET['course']))
{
    $course = urldecode($_GET['course']);
    require_once 'form_data_course.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_course.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/course.php';
        $dbh_course = new course;

        $object_name = 'dbh_course';
        require 'components/create_form_data.php';

        $dbh_course->delete($arr_form_data);


        redirect("listview_course.php?$query_string");
    }
}
require 'subclasses/course_html.php';
$html = new course_html;
$html->draw_header('Delete Course', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('course');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();