<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit xrefstudentcourse');

if(isset($_GET['student_id']) && isset($_GET['course']) && isset($_GET['term_id']))
{
    $student_id = urldecode($_GET['student_id']);
    $course = urldecode($_GET['course']);
    $term_id = urldecode($_GET['term_id']);
    require 'form_data_xrefstudentcourse.php';
    $orig_student_id = $student_id;
    $orig_course = $course;
    $orig_term_id = $term_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/xrefstudentcourse.php';
    $dbh_xrefstudentcourse = new xrefstudentcourse;

    $object_name = 'dbh_xrefstudentcourse';
    require 'components/create_form_data.php';
    $arr_form_data['orig_student_id'] = $_POST['orig_student_id'];
    $arr_form_data['orig_course'] = $_POST['orig_course'];
    $arr_form_data['orig_term_id'] = $_POST['orig_term_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_xrefstudentcourse.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_xrefstudentcourse->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_xrefstudentcourse->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_xrefstudentcourse->edit($arr_form_data);

            redirect("listview_xrefstudentcourse.php?$query_string");
        }
    }
}
require 'subclasses/xrefstudentcourse_html.php';
$html = new xrefstudentcourse_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_student_id');
$html->draw_hidden('orig_course');
$html->draw_hidden('orig_term_id');
$html->draw_controls('edit');

$html->draw_footer();